/**
 * Wrike Custom Field IDs and Item Type IDs
 *
 * This file contains all the Wrike custom field IDs used throughout the application.
 * Fields are organized alphabetically for easy lookup.
 *
 * Source: wrike-custom-fields.json
 */

export const WRIKE_CUSTOM_FIELDS = {
  // A
  ACTIVE: "IEADYYMRJUAJFPY4",
  AGE: "IEADYYMRJUAJFSWF",
  AUTO_EXPIRE: "IEADYYMRJUAJFQSF",

  // B
  BILLING_ADDRESS: "IEADYYMRJUAJJ7RD",
  BILLING_ADDRESS_ID: "IEADYYMRJUAJFS3J",

  // C
  CLOSING_POTENTIAL: "IEADYYMRJUAJFQR7",
  COMPANY_ID: "IEADYYMRJUAJFSXP",
  COMPANY_NAME: "IEADYYMRJUAJFSXR",
  COMPANY_PHONE: "IEADYYMRJUAJFSXV",
  COMPANY_SPECIAL_NOTES: "IEADYYMRJUAJFUC5",
  CREATED_AT: "IEADYYMRJUAJFSVG",
  CREATED_BY: "IEADYYMRJUAJIFEN",
  CREATED_BY_ID: "IEADYYMRJUAJFSW5",
  CUSTOMER_NOTE: "IEADYYMRJUAJFSWP",
  CUSTOMER_PO_DATE: "IEADYYMRJUAJFQSE",
  CUSTOMER_PO_NUMBER: "IEADYYMRJUAJFQSC",

  // D
  DESCRIPTION: "IEADYYMRJUAJFPZB",
  DOWNPAYMENT_PERCENT: "IEADYYMRJUAJFQSH",

  // E
  ESTIMATOR: "IEADYYMRJUAJIFEM",
  EXPIRY_DATE: "IEADYYMRJUAJFP27",

  // F
  FINANCE_CHARGES_IN_DOLLARS: "IEADYYMRJUAJFUCP",
  FINANCE_CHARGES_IS_PERCENT: "IEADYYMRJUAJFUCV",
  FINANCE_CHARGES_PERCENT: "IEADYYMRJUAJFUCY",
  FINANCE_CHARGES_TAXABLE: "IEADYYMRJUAJFUCR",
  FINANCE_CHARGES_TAX_IN_DOLLARS: "IEADYYMRJUAJFUC2",
  FULLY_INVOICED: "IEADYYMRJUAJFS3H",

  // I
  IN_HAND_DATE: "IEADYYMRJUAJFSWY",
  IN_HAND_DATE_SALES_ORDER: "IEADYYMRJUAJKGQJ",
  INVOICED: "IEADYYMRJUAJFS3G",
  INSTALL_ADDRESS: "IEADYYMRJUAJIG5N",

  // L
  LAST_EMAILED_DATE: "IEADYYMRJUAJFSWJ",
  LAST_INVOICED_AT: "IEADYYMRJUAJFS3A",
  LAST_INVOICED_ON: "IEADYYMRJUAJFS3F",
  LAST_NOTE: "IEADYYMRJUAJFSWE",
  LEAD_SOURCE_ID: "IEADYYMRJUAJFSXW",
  LINE_ITEMS: "IEADYYMRJUAJFSX2",
  LINKED_ORDERS: "IEADYYMRJUAKBTE2",
  LINKED_QUOTE: "IEADYYMRJUAKBTEZ",

  // M
  MISC_CHARGES_IS_PERCENT: "IEADYYMRJUAJFS5J",
  MISC_CHARGES_LABEL: "IEADYYMRJUAJFS5G",
  MISC_CHARGES_PERCENT: "IEADYYMRJUAJFUCB",
  MISC_CHARGES_TAXABLE: "IEADYYMRJUAJFS5C",
  MISC_CHARGES_TAX_IN_DOLLARS: "IEADYYMRJUAJFUCD",

  // N
  NEXT_CONTENT_DATE: "IEADYYMRJUAJFQR5",

  // O
  ORDER_PAYMENTS: "IEADYYMRJUAJFUDZ",

  // P
  PAYMENT_TOTAL: "IEADYYMRJUAJFS26",
  POTENTIAL_CLOSING_DATE: "IEADYYMRJUAJFQR6",
  PRIMARY_CONTACT_EMAIL: "IEADYYMRJUAJFSXI",
  PRIMARY_CONTACT_ID: "IEADYYMRJUAJFSXK",
  PRIMARY_CONTACT_NAME: "IEADYYMRJUAJFSXH",
  PRIMARY_CONTACT_PHONE: "IEADYYMRJUAJFSXJ",
  PRIMARY_SALES_REP_ID: "IEADYYMRJUAJFSXM",
  PRIMARY_SALES_REP_INITIALS: "IEADYYMRJUAJFSXO",
  PRODUCTION_DUE_DATE: "IEADYYMRJUAJKGSN",
  PRODUCTION_MANAGER: "IEADYYMRJUAJIFEE",
  PRODUCTION_MANAGER_ID: "IEADYYMRJUAJFS37",
  PROJECT_MANAGER: "IEADYYMRJUAJIFD5",
  PROJECT_MANAGER_ID: "IEADYYMRJUAJFS4A",
  PURCHASE_ORDERS: "IEADYYMRJUAJFUD6",
  PURCHASE_ORDER_LINE_ITEMS_TOTAL_PRICE: "IEADYYMRJUAJFUD4",

  // Q
  QUICK_QUOTE: "IEADYYMRJUAJFSWX",
  QUOTE_FOR: "IEADYYMRJUAJFSWM",

  // R
  REMAINING_BALANCE: "IEADYYMRJUAJFS27",
  RELATED_TRANSACTIONS: "IEADYYMRJUAJFUDX",

  // S
  SALES_ORDERS: "IEADYYMRJUAJFSXF",
  SALES_REP: "IEADYYMRJUAJFSXL",
  SALES_TAX_ID: "IEADYYMRJUAJFS3N",
  SETUP_CHARGES_IN_DOLLARS: "IEADYYMRJUAJFS4C",
  SETUP_CHARGES_IS_PERCENT: "IEADYYMRJUAJFS4R",
  SETUP_CHARGES_PERCENT: "IEADYYMRJUAJFS4U",
  SETUP_CHARGES_TAXABLE: "IEADYYMRJUAJFS4M",
  SETUP_CHARGES_TAX_IN_DOLLARS: "IEADYYMRJUAJFS4V",
  SHIPPED_DATE: "IEADYYMRJUAJFQSL",
  SHIPPING_ADDRESS: "IEADYYMRJUAJJ7RA",
  SHIPPING_ADDRESS_ID: "IEADYYMRJUAJFS3K",
  SHIPPING_CHARGES_IN_DOLLARS: "IEADYYMRJUAJFUCE",
  SHIPPING_CHARGES_IS_PERCENT: "IEADYYMRJUAJFUCJ",
  SHIPPING_CHARGES_PERCENT: "IEADYYMRJUAJFUCK",
  SHIPPING_CHARGES_TAXABLE: "IEADYYMRJUAJFUCI",
  SHIPPING_CHARGES_TAX_IN_DOLLARS: "IEADYYMRJUAJFUCM",
  SHIPPING_DATE: "IEADYYMRJUAJKGSA",
  SHIPPING_METHOD_ID: "IEADYYMRJUAJFS3Z",
  SHIPPING_TRACKING: "IEADYYMRJUAJFQSJ",
  SHOPVOX_ID: "IEADYYMRJUAJFPCR",
  SHOPVOX_QUOTE_LINK: "IEADYYMRJUAJG7E4",
  SHOPVOX_SALES_ORDER_LINK: "IEADYYMRJUAJJEVR",
  SIGNATURES: "IEADYYMRJUAJFUED",
  SITE: "IEADYYMRJUAJFSWW",
  SO_CREATED_DATE: "IEADYYMRJUAJFPZC",
  SO_SUBTOTAL: "IEADYYMRJUAJFPZD",
  SV_STATUS: "IEADYYMRJUAJFP2V",

  // T
  TARGET_INSTALL_DATE: "IEADYYMRJUAJKDIX",
  TAX: "IEADYYMRJUAJFPZF",
  TAX_AGENCY: "IEADYYMRJUAJFUDS",
  TAX_CODE: "IEADYYMRJUAJFUDT",
  TAX_ID: "IEADYYMRJUAJFUDD",
  TAX_NAME: "IEADYYMRJUAJFUDE",
  TAX_RATE: "IEADYYMRJUAJFUDG",
  TAX_RATE_IN_PERCENT: "IEADYYMRJUAJFUDH",
  TERM_CODE_DAYS: "IEADYYMRJUAJFUDC",
  TERM_CODE_ID: "IEADYYMRJUAJFUC6",
  TERM_CODE_NAME: "IEADYYMRJUAJFUDA",
  TERM_CODE_TYPE: "IEADYYMRJUAJFUDB",
  TITLE: "IEADYYMRJUAJFPY5",
  TOTAL: "IEADYYMRJUAJFPZH",
  TOTAL_PRICE_WITH_TAX: "IEADYYMRJUAJFPZH",
  TOTAL_TAX: "IEADYYMRJUAJFPZF",
  TXN_NUMBER: "IEADYYMRJUAJFP3B",

  // U
  UPDATED_AT: "IEADYYMRJUAJFSWB",
  UPDATED_BY: "IEADYYMRJUAJFUDW",

  // W
  WOSOS: "IEADYYMRJUAJJ6HA",
  WORK_ORDER_LINKS: "IEADYYMRJUAJJ6HA",
} as const;

/**
 * Wrike Custom Item Type IDs
 */
export const WRIKE_ITEM_TYPES = {
  QUOTE: "IEADYYMRPIAFP7UJ",
  SALES_ORDER: "IEADYYMRPIAFP7OS",
} as const;

/**
 * Type definitions for better TypeScript support
 */
export type WrikeCustomFieldId =
  (typeof WRIKE_CUSTOM_FIELDS)[keyof typeof WRIKE_CUSTOM_FIELDS];
export type WrikeItemTypeId =
  (typeof WRIKE_ITEM_TYPES)[keyof typeof WRIKE_ITEM_TYPES];

/**
 * Legacy address field IDs - kept for backward compatibility
 * @deprecated Use WRIKE_CUSTOM_FIELDS.SHIPPING_ADDRESS, BILLING_ADDRESS, INSTALL_ADDRESS instead
 */
export const WRIKE_ADDRESS_FIELD_IDS = {
  SHIPPING_ADDRESS: WRIKE_CUSTOM_FIELDS.SHIPPING_ADDRESS,
  BILLING_ADDRESS: WRIKE_CUSTOM_FIELDS.BILLING_ADDRESS,
  INSTALL_ADDRESS: WRIKE_CUSTOM_FIELDS.INSTALL_ADDRESS,
} as const;
